name: Mango
description: Mango App - Your Nutritional Facts in One Click
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 0.19.0
  hexcolor: 1.0.6
  carousel_slider: 2.3.1
  image_picker: 0.6.7
  http: 0.12.2
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
 
  fonts:
    - family: BalooTammudu2
      fonts:
        - asset: fonts/BalooTammudu2-Regular.ttf
        - asset: fonts/BalooTammudu2-ExtraBold.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
